### ISSUE TITLE
Module JSON Changes getting triggered for modules using `entity` in their packs in v9

### ISSUE THREAD

**Issue by arcanistzed** [League-of-Foundry-Developers/foundryvtt-devMode#26]
**Environment Details**
- Foundry Core Version: v9d2
- System & Version: dnd5e 1.5.5
- OS & Browser: Chrome Linux Mint
- Hosting: Selfhosted NodeJS

**Describe the bug**
The new "Module JSON Changes" feature is getting triggered when using a module that still uses the `entity` field in their packs in v9. Core changes this field to `type` which make Dev Mode think it was changed.

**To Reproduce**
1. Install module using `entity` in packs on a v9 instance
2. See notification and console message describing a change

**Expected behavior**
I would expect Dev Mode to detect if this is the only change before alerting me. Otherwise, it could be beneficial to allow users to choose only certain modules which they care about changes to (perhaps keyed off of the `author` name).

**Screenshots**
![image](https://user-images.githubusercontent.com/82790112/143370660-7ad3a19c-aa68-4389-a5b9-60c909731dc3.png)

**Comment by akrigline** [comment]
@arcanistzed can you re-test this on latest v9 stable, this might have been solved by something core did.

**Comment by arcanistzed** [comment]
@akrigline Nope. I tested again with MidiQoL on 9.242 and it still happens
